name: guillotina_gcloudstorage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.16]

    steps:
      # Checkout the repository first
      - uses: actions/checkout@v2

      # Setup the python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Linters and typing
      - name: Pre-checks
        run: |
          make pre-checks

      # Run tests
      - name: Run tests
        run: |
          # Commented out until we find a mocked GCS
          # make tests
